const group_types = [
    {
        id: 18,
        name: "Party",
        image: "beanfest.jpg",
        max_players: null,
        max_player_options: null,
        required_location_type: "playground",
        implied_location: null,
        possible_locations: null,
        game: 1,
        options: [],
    },
    {
        id: 20,
        name: "Building",
        image: "building.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "street",
        implied_location: null,
        possible_locations: null,
        game: 2,
        options: [
            {
                id: 16,
                name: "Stories",
                type: 20,
                optional: true,
                values: [
                    {
                        id: 50,
                        name: "One Story",
                        option: 16,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 51,
                        name: "Two Story",
                        option: 16,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 52,
                        name: "Three Story",
                        option: 16,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 53,
                        name: "Four Story",
                        option: 16,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 54,
                        name: "Five Story",
                        option: 16,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 93,
                        name: "Six Story",
                        option: 16,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
            {
                id: 17,
                name: "Cog Type",
                type: 20,
                optional: true,
                values: [
                    {
                        id: 55,
                        name: "Sellbot",
                        option: 17,
                        image_override: "building_sellbot.jpg",
                        prefix: true,
                    },
                    {
                        id: 56,
                        name: "Cashbot",
                        option: 17,
                        image_override: "building_cashbot.jpg",
                        prefix: true,
                    },
                    {
                        id: 57,
                        name: "Lawbot",
                        option: 17,
                        image_override: "building_lawbot.jpg",
                        prefix: true,
                    },
                    {
                        id: 58,
                        name: "Bossbot",
                        option: 17,
                        image_override: "building_bossbot.jpg",
                        prefix: true,
                    },
                    {
                        id: 94,
                        name: "Boardbot",
                        option: 17,
                        image_override: "building_boardbot.jpg",
                        prefix: true,
                    },
                ],
            },
            {
                id: 46,
                name: "Training",
                type: 20,
                optional: true,
                values: [
                    {
                        id: 146,
                        name: "Training",
                        option: 46,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 147,
                        name: "Fast",
                        option: 46,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
        ],
    },
    {
        id: 30,
        name: "Toontask",
        image: "toontask.jpg",
        max_players: 8,
        max_player_options: null,
        required_location_type: null,
        implied_location: null,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 23,
        name: "Mint",
        image: "mint.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "coghq",
        implied_location: 66,
        possible_locations: null,
        game: 2,
        options: [
            {
                id: 22,
                name: "Type",
                type: 23,
                optional: true,
                values: [
                    {
                        id: 67,
                        name: "Coin",
                        option: 22,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 68,
                        name: "Dollar",
                        option: 22,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 69,
                        name: "Bullion",
                        option: 22,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
            {
                id: 23,
                name: "Gags",
                type: 23,
                optional: true,
                values: [
                    {
                        id: 70,
                        name: "Sound",
                        option: 23,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 71,
                        name: "Soundless",
                        option: 23,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
            {
                id: 34,
                name: "Length",
                type: 23,
                optional: true,
                values: [
                    {
                        id: 108,
                        name: "Minimal",
                        option: 34,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 109,
                        name: "Full",
                        option: 34,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 110,
                        name: "For Training",
                        option: 34,
                        image_override: null,
                        prefix: false,
                    },
                ],
            },
        ],
    },
    {
        id: 21,
        name: "Factory",
        image: "factory.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "coghq",
        implied_location: 65,
        possible_locations: null,
        game: 2,
        options: [
            {
                id: 18,
                name: "Length",
                type: 21,
                optional: true,
                values: [
                    {
                        id: 59,
                        name: "Short",
                        option: 18,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 60,
                        name: "Long",
                        option: 18,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 117,
                        name: "For Training",
                        option: 18,
                        image_override: null,
                        prefix: false,
                    },
                ],
            },
            {
                id: 19,
                name: "Entrance",
                type: 21,
                optional: true,
                values: [
                    {
                        id: 61,
                        name: "Front",
                        option: 19,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 62,
                        name: "Side",
                        option: 19,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
            {
                id: 20,
                name: "Gags",
                type: 21,
                optional: true,
                values: [
                    {
                        id: 63,
                        name: "Sound",
                        option: 20,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 64,
                        name: "Soundless",
                        option: 20,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
            {
                id: 40,
                name: "Battles",
                type: 21,
                optional: true,
                values: [
                    {
                        id: 124,
                        name: "Split",
                        option: 40,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
        ],
    },
    {
        id: 12,
        name: "Gag Training",
        image: "training.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: null,
        implied_location: null,
        possible_locations: null,
        game: 1,
        options: [
            {
                id: 11,
                name: "Type",
                type: 12,
                optional: true,
                values: [
                    {
                        id: 30,
                        name: "Toon-Up",
                        option: 11,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 31,
                        name: "Trap",
                        option: 11,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 32,
                        name: "Lure",
                        option: 11,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 33,
                        name: "Sound",
                        option: 11,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 34,
                        name: "Throw",
                        option: 11,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 35,
                        name: "Squirt",
                        option: 11,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 36,
                        name: "Drop",
                        option: 11,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
        ],
    },
    {
        id: 34,
        name: "Trolley",
        image: "cc_trolley.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "playground",
        implied_location: null,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 25,
        name: "Lawfice",
        image: "lawfice.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "coghq",
        implied_location: 67,
        possible_locations: null,
        game: 2,
        options: [
            {
                id: 24,
                name: "Office",
                type: 25,
                optional: true,
                values: [
                    {
                        id: 72,
                        name: "A",
                        option: 24,
                        image_override: null,
                        prefix: false,
                    },
                    {
                        id: 73,
                        name: "B",
                        option: 24,
                        image_override: null,
                        prefix: false,
                    },
                    {
                        id: 74,
                        name: "C",
                        option: 24,
                        image_override: null,
                        prefix: false,
                    },
                ],
            },
            {
                id: 35,
                name: "Length",
                type: 25,
                optional: true,
                values: [
                    {
                        id: 111,
                        name: "Minimal",
                        option: 35,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 112,
                        name: "Full",
                        option: 35,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 113,
                        name: "For Training",
                        option: 35,
                        image_override: null,
                        prefix: false,
                    },
                ],
            },
        ],
    },
    {
        id: 38,
        name: "Fishing",
        image: "cc_fishing.jpg",
        max_players: null,
        max_player_options: null,
        required_location_type: null,
        implied_location: null,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 39,
        name: "Derrick Man",
        image: "derrick_man.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "street",
        implied_location: 33,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 40,
        name: "Director of Land Acquisition",
        image: "dola.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "street",
        implied_location: 38,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 41,
        name: "Director of Public Relations",
        image: "dopr.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "playground",
        implied_location: 40,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 42,
        name: "Director of Public Affairs",
        image: "dopa.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "coghq",
        implied_location: 68,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 33,
        name: "Golfing",
        image: "cndgolf.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "playground",
        implied_location: 63,
        possible_locations: null,
        game: 2,
        options: [
            {
                id: 29,
                name: "Type",
                type: 33,
                optional: true,
                values: [
                    {
                        id: 91,
                        name: "Competitive",
                        option: 29,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 92,
                        name: "Win Trading",
                        option: 29,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
        ],
    },
    {
        id: 68,
        name: "Fishing",
        image: "fishing.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: null,
        implied_location: null,
        possible_locations: null,
        game: 1,
        options: [],
    },
    {
        id: 69,
        name: "Fishing",
        image: "fishing.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: null,
        implied_location: null,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 28,
        name: "CEO",
        image: "ceo.jpg",
        max_players: 8,
        max_player_options: [2, 4, 6, 8],
        required_location_type: "coghq",
        implied_location: 68,
        possible_locations: null,
        game: 2,
        options: [
            {
                id: 30,
                name: "Boss Tier",
                type: 28,
                optional: true,
                values: [
                    {
                        id: 95,
                        name: "Tier 1",
                        option: 30,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 96,
                        name: "Tier 2",
                        option: 30,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 97,
                        name: "Tier 3",
                        option: 30,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
        ],
    },
    {
        id: 24,
        name: "CFO",
        image: "cfo.jpg",
        max_players: 8,
        max_player_options: [2, 4, 6, 8],
        required_location_type: "coghq",
        implied_location: 66,
        possible_locations: null,
        game: 2,
        options: [
            {
                id: 31,
                name: "Boss Tier",
                type: 24,
                optional: true,
                values: [
                    {
                        id: 98,
                        name: "Tier 1",
                        option: 31,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 99,
                        name: "Tier 2",
                        option: 31,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 100,
                        name: "Tier 3",
                        option: 31,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
        ],
    },
    {
        id: 22,
        name: "VP",
        image: "vp.jpg",
        max_players: 8,
        max_player_options: [2, 4, 6, 8],
        required_location_type: "coghq",
        implied_location: 65,
        possible_locations: null,
        game: 2,
        options: [
            {
                id: 32,
                name: "Boss Tier",
                type: 22,
                optional: true,
                values: [
                    {
                        id: 101,
                        name: "Tier 1",
                        option: 32,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 102,
                        name: "Tier 2",
                        option: 32,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 103,
                        name: "Tier 3",
                        option: 32,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
        ],
    },
    {
        id: 26,
        name: "CLO",
        image: "clo.jpg",
        max_players: 8,
        max_player_options: [2, 4, 6, 8],
        required_location_type: "coghq",
        implied_location: 67,
        possible_locations: null,
        game: 2,
        options: [
            {
                id: 33,
                name: "Boss Tier",
                type: 26,
                optional: true,
                values: [
                    {
                        id: 104,
                        name: "Tier 1",
                        option: 33,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 105,
                        name: "Tier 2",
                        option: 33,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 106,
                        name: "Tier 3",
                        option: 33,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 119,
                        name: "Overclocked",
                        option: 33,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
        ],
    },
    {
        id: 31,
        name: "Gag Training",
        image: "training.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: null,
        implied_location: null,
        possible_locations: null,
        game: 2,
        options: [
            {
                id: 26,
                name: "Type",
                type: 31,
                optional: true,
                values: [
                    {
                        id: 79,
                        name: "Toon-Up",
                        option: 26,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 80,
                        name: "Trap",
                        option: 26,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 81,
                        name: "Lure",
                        option: 26,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 82,
                        name: "Sound",
                        option: 26,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 83,
                        name: "Throw",
                        option: 26,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 84,
                        name: "Squirt",
                        option: 26,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 85,
                        name: "Drop",
                        option: 26,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 107,
                        name: "Zap",
                        option: 26,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
        ],
    },
    {
        id: 32,
        name: "Kart Racing",
        image: "karting.jpg",
        max_players: 8,
        max_player_options: null,
        required_location_type: "playground",
        implied_location: 64,
        possible_locations: null,
        game: 2,
        options: [
            {
                id: 28,
                name: "Type",
                type: 32,
                optional: true,
                values: [
                    {
                        id: 89,
                        name: "Competitive",
                        option: 28,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 90,
                        name: "For Win Trading",
                        option: 28,
                        image_override: null,
                        prefix: false,
                    },
                ],
            },
        ],
    },
    {
        id: 44,
        name: "Table Game",
        image: "cc_table.jpg",
        max_players: 6,
        max_player_options: null,
        required_location_type: "playground",
        implied_location: 63,
        possible_locations: null,
        game: 2,
        options: [
            {
                id: 38,
                name: "Type",
                type: 44,
                optional: true,
                values: [
                    {
                        id: 120,
                        name: "Chess",
                        option: 38,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 121,
                        name: "Checkers",
                        option: 38,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 122,
                        name: "TOONO",
                        option: 38,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
        ],
    },
    {
        id: 46,
        name: "Sellbot Field Office",
        image: "__sfo__",
        max_players: 4,
        max_player_options: null,
        required_location_type: "street",
        implied_location: null,
        possible_locations: [10, 16, 18, 15, 19, 1, 2, 26, 20, 25, 29],
        game: 1,
        options: [
            {
                id: 41,
                name: "Stars",
                type: 46,
                optional: true,
                values: [
                    {
                        id: 125,
                        name: "One Star",
                        option: 41,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 126,
                        name: "Two Star",
                        option: 41,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 127,
                        name: "Three Star",
                        option: 41,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
        ],
    },
    {
        id: 5,
        name: "CFO",
        image: "cfo.jpg",
        max_players: 8,
        max_player_options: [2, 4, 6, 8],
        required_location_type: "coghq",
        implied_location: 5,
        possible_locations: null,
        game: 1,
        options: [],
    },
    {
        id: 49,
        name: "Four Star Field Office",
        image: "playground_field_office.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "playground",
        implied_location: 7,
        possible_locations: null,
        game: 1,
        options: [],
    },
    {
        id: 1,
        name: "Building",
        image: "building.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "street",
        implied_location: null,
        possible_locations: null,
        game: 1,
        options: [
            {
                id: 1,
                name: "Stories",
                type: 1,
                optional: true,
                values: [
                    {
                        id: 1,
                        name: "One Story",
                        option: 1,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 2,
                        name: "Two Story",
                        option: 1,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 3,
                        name: "Three Story",
                        option: 1,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 4,
                        name: "Four Story",
                        option: 1,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 5,
                        name: "Five Story",
                        option: 1,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
            {
                id: 2,
                name: "Cog Type",
                type: 1,
                optional: true,
                values: [
                    {
                        id: 6,
                        name: "Sellbot",
                        option: 2,
                        image_override: "building_sellbot.jpg",
                        prefix: true,
                    },
                    {
                        id: 7,
                        name: "Cashbot",
                        option: 2,
                        image_override: "building_cashbot.jpg",
                        prefix: true,
                    },
                    {
                        id: 8,
                        name: "Lawbot",
                        option: 2,
                        image_override: "building_lawbot.jpg",
                        prefix: true,
                    },
                    {
                        id: 9,
                        name: "Bossbot",
                        option: 2,
                        image_override: "building_bossbot.jpg",
                        prefix: true,
                    },
                ],
            },
            {
                id: 45,
                name: "Training",
                type: 1,
                optional: true,
                values: [
                    {
                        id: 144,
                        name: "Training",
                        option: 45,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 145,
                        name: "Fast",
                        option: 45,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
        ],
    },
    {
        id: 2,
        name: "Factory",
        image: "factory.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "coghq",
        implied_location: 23,
        possible_locations: null,
        game: 1,
        options: [
            {
                id: 3,
                name: "Length",
                type: 2,
                optional: true,
                values: [
                    {
                        id: 10,
                        name: "Short",
                        option: 3,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 11,
                        name: "Long",
                        option: 3,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 157,
                        name: "For Training",
                        option: 3,
                        image_override: null,
                        prefix: false,
                    },
                ],
            },
            {
                id: 4,
                name: "Type",
                type: 2,
                optional: true,
                values: [
                    {
                        id: 12,
                        name: "Scrap",
                        option: 4,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 13,
                        name: "Steel",
                        option: 4,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
            {
                id: 5,
                name: "Gags",
                type: 2,
                optional: true,
                values: [
                    {
                        id: 14,
                        name: "Sound",
                        option: 5,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 15,
                        name: "Soundless",
                        option: 5,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
        ],
    },
    {
        id: 4,
        name: "Mint",
        image: "mint.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "coghq",
        implied_location: 5,
        possible_locations: null,
        game: 1,
        options: [
            {
                id: 7,
                name: "Type",
                type: 4,
                optional: true,
                values: [
                    {
                        id: 18,
                        name: "Coin",
                        option: 7,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 20,
                        name: "Bullion",
                        option: 7,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
            {
                id: 8,
                name: "Gags",
                type: 4,
                optional: true,
                values: [
                    {
                        id: 21,
                        name: "Sound",
                        option: 8,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 22,
                        name: "Soundless",
                        option: 8,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
            {
                id: 47,
                name: "Length",
                type: 4,
                optional: true,
                values: [
                    {
                        id: 148,
                        name: "Minimal",
                        option: 47,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 149,
                        name: "Full",
                        option: 47,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 150,
                        name: "For Training",
                        option: 47,
                        image_override: null,
                        prefix: false,
                    },
                ],
            },
        ],
    },
    {
        id: 6,
        name: "DA Office",
        image: "da.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "coghq",
        implied_location: 12,
        possible_locations: null,
        game: 1,
        options: [
            {
                id: 9,
                name: "Wing",
                type: 6,
                optional: true,
                values: [
                    {
                        id: 23,
                        name: "Junior",
                        option: 9,
                        image_override: null,
                        prefix: false,
                    },
                    {
                        id: 26,
                        name: "Senior",
                        option: 9,
                        image_override: null,
                        prefix: false,
                    },
                ],
            },
            {
                id: 48,
                name: "Length",
                type: 6,
                optional: true,
                values: [
                    {
                        id: 151,
                        name: "Minimal",
                        option: 48,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 152,
                        name: "Full",
                        option: 48,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 153,
                        name: "For Training",
                        option: 48,
                        image_override: null,
                        prefix: false,
                    },
                ],
            },
        ],
    },
    {
        id: 11,
        name: "Toontask",
        image: "toontask.jpg",
        max_players: 8,
        max_player_options: null,
        required_location_type: null,
        implied_location: null,
        possible_locations: null,
        game: 1,
        options: [],
    },
    {
        id: 13,
        name: "Kart Racing",
        image: "karting.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "playground",
        implied_location: 11,
        possible_locations: null,
        game: 1,
        options: [
            {
                id: 13,
                name: "Type",
                type: 13,
                optional: true,
                values: [
                    {
                        id: 44,
                        name: "Competitive",
                        option: 13,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 45,
                        name: "For Win Trading",
                        option: 13,
                        image_override: null,
                        prefix: false,
                    },
                ],
            },
        ],
    },
    {
        id: 14,
        name: "Chip 'n Dale Golfing",
        image: "cndgolf.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "playground",
        implied_location: 6,
        possible_locations: null,
        game: 1,
        options: [
            {
                id: 14,
                name: "Type",
                type: 14,
                optional: true,
                values: [
                    {
                        id: 46,
                        name: "Competitive",
                        option: 14,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 47,
                        name: "Win Trading",
                        option: 14,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
            {
                id: 50,
                name: "Difficulty",
                type: 14,
                optional: true,
                values: [
                    {
                        id: 158,
                        name: "Easy",
                        option: 50,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 159,
                        name: "Medium",
                        option: 50,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 160,
                        name: "Hard",
                        option: 50,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
        ],
    },
    {
        id: 15,
        name: "Trolley",
        image: "trolley.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "playground",
        implied_location: null,
        possible_locations: null,
        game: 1,
        options: [],
    },
    {
        id: 16,
        name: "Table Game",
        image: "table.jpg",
        max_players: null,
        max_player_options: null,
        required_location_type: "playground",
        implied_location: 6,
        possible_locations: null,
        game: 1,
        options: [
            {
                id: 12,
                name: "Type",
                type: 16,
                optional: true,
                values: [
                    {
                        id: 37,
                        name: "Checkers",
                        option: 12,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 38,
                        name: "Chinese Checkers",
                        option: 12,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 39,
                        name: "Find Four",
                        option: 12,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
        ],
    },
    {
        id: 10,
        name: "Beanfest",
        image: "beanfest.jpg",
        max_players: null,
        max_player_options: null,
        required_location_type: null,
        implied_location: null,
        possible_locations: null,
        game: 1,
        options: [],
    },
    {
        id: 50,
        name: "Duck Shuffler",
        image: "duck_shuffler.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "street",
        implied_location: null,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 51,
        name: "Prethinker",
        image: "prethinker.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "playground",
        implied_location: 30,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 52,
        name: "Plutocrat",
        image: "plutocrat.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "street",
        implied_location: 55,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 53,
        name: "Multislacker",
        image: "multislacker.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "coghq",
        implied_location: 65,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 54,
        name: "Rainmaker",
        image: "rainmaker.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "street",
        implied_location: 37,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 55,
        name: "Pacesetter",
        image: "pacesetter.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "street",
        implied_location: 60,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 56,
        name: "Major Player",
        image: "major_player.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "street",
        implied_location: 53,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 57,
        name: "Bellringer",
        image: "bellringer.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "street",
        implied_location: null,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 58,
        name: "Chainsaw Consultant",
        image: "chainsaw_consultant.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "street",
        implied_location: 71,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 59,
        name: "Deep Diver",
        image: "deep_diver.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "street",
        implied_location: null,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 60,
        name: "Mouthpiece",
        image: "mouthpiece.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "street",
        implied_location: null,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 61,
        name: "Featherbedder",
        image: "featherbedder.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "street",
        implied_location: null,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 62,
        name: "Gatekeeper",
        image: "gatekeeper.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "street",
        implied_location: null,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 63,
        name: "Treekiller",
        image: "treekiller.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "street",
        implied_location: null,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 64,
        name: "Firestarter",
        image: "firestarter.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "street",
        implied_location: null,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 65,
        name: "Witch Hunter",
        image: "witch_hunter.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "playground",
        implied_location: 40,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 66,
        name: "Building Marathon",
        image: "building_marathon.jpg",
        max_players: null,
        max_player_options: null,
        required_location_type: "playground",
        implied_location: null,
        possible_locations: null,
        game: 1,
        options: [],
    },
    {
        id: 67,
        name: "Building Marathon",
        image: "building_marathon.jpg",
        max_players: null,
        max_player_options: null,
        required_location_type: "playground",
        implied_location: null,
        possible_locations: null,
        game: 2,
        options: [],
    },
    {
        id: 3,
        name: "VP",
        image: "vp.jpg",
        max_players: 8,
        max_player_options: [2, 4, 6, 8],
        required_location_type: "coghq",
        implied_location: 23,
        possible_locations: null,
        game: 1,
        options: [
            {
                id: 6,
                name: "Shopping",
                type: 3,
                optional: true,
                values: [
                    {
                        id: 16,
                        name: "No Shopping",
                        option: 6,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 17,
                        name: "SOS Shopping",
                        option: 6,
                        image_override: "vp_sosshopping.jpg",
                        prefix: true,
                    },
                    {
                        id: 161,
                        name: "Low Star Shopping",
                        option: 6,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
        ],
    },
    {
        id: 9,
        name: "CEO",
        image: "ceo.jpg",
        max_players: 8,
        max_player_options: [2, 4, 6, 8],
        required_location_type: "coghq",
        implied_location: 4,
        possible_locations: null,
        game: 1,
        options: [],
    },
    {
        id: 7,
        name: "CJ",
        image: "cj.jpg",
        max_players: 8,
        max_player_options: [2, 4, 6, 8],
        required_location_type: "coghq",
        implied_location: 12,
        possible_locations: null,
        game: 1,
        options: [],
    },
    {
        id: 27,
        name: "Cog Golf Course",
        image: "golf.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "coghq",
        implied_location: 68,
        possible_locations: null,
        game: 2,
        options: [
            {
                id: 25,
                name: "Course",
                type: 27,
                optional: true,
                values: [
                    {
                        id: 76,
                        name: "Front 3",
                        option: 25,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 77,
                        name: "Middle 6",
                        option: 25,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 78,
                        name: "Back 9",
                        option: 25,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
            {
                id: 36,
                name: "Length",
                type: 27,
                optional: true,
                values: [
                    {
                        id: 114,
                        name: "Minimal",
                        option: 36,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 115,
                        name: "Full",
                        option: 36,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 116,
                        name: "For Training",
                        option: 36,
                        image_override: null,
                        prefix: false,
                    },
                ],
            },
        ],
    },
    {
        id: 8,
        name: "Cog Golf Course",
        image: "golf.jpg",
        max_players: 4,
        max_player_options: null,
        required_location_type: "coghq",
        implied_location: 4,
        possible_locations: null,
        game: 1,
        options: [
            {
                id: 10,
                name: "Course",
                type: 8,
                optional: true,
                values: [
                    {
                        id: 27,
                        name: "First Fairway",
                        option: 10,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 29,
                        name: "Final Fringe",
                        option: 10,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
            {
                id: 49,
                name: "Length",
                type: 8,
                optional: true,
                values: [
                    {
                        id: 154,
                        name: "Minimal",
                        option: 49,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 155,
                        name: "Full",
                        option: 49,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 156,
                        name: "For Training",
                        option: 49,
                        image_override: null,
                        prefix: false,
                    },
                ],
            },
        ],
    },
    {
        id: 17,
        name: "Doodle Training",
        image: "doodle.jpg",
        max_players: null,
        max_player_options: null,
        required_location_type: null,
        implied_location: null,
        possible_locations: null,
        game: 1,
        options: [
            {
                id: 42,
                name: "Trick",
                type: 17,
                optional: true,
                values: [
                    {
                        id: 128,
                        name: "Jump",
                        option: 42,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 129,
                        name: "Beg",
                        option: 42,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 130,
                        name: "Play Dead",
                        option: 42,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 131,
                        name: "Rollover",
                        option: 42,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 132,
                        name: "Backflip",
                        option: 42,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 133,
                        name: "Dance",
                        option: 42,
                        image_override: null,
                        prefix: true,
                    },
                    {
                        id: 134,
                        name: "Speak",
                        option: 42,
                        image_override: null,
                        prefix: true,
                    },
                ],
            },
        ],
    },
];

export function evaluateGroupName(group: any) {
    const type = group_types.filter(t => t.id === group.type)[0];
    if (!type) return "Unknown Group? 0__0";

    let name = type.name;

    // handle options, which are described in groups as "options": { option_type: option_value, ... }
    if (group.options && Object.keys(group.options).length > 0) {
        // name = name + JSON.stringify(group.options);

        Object.keys(group.options).forEach((optionType, index) => {
            const optionValue = group.options[optionType];

            console.log("Group has option", optionType, "equalling", optionValue);

            const optionTypeName = group_types.filter(t => t.id === group.type)[0]?.options.filter((o: any) => o.id === parseInt(optionType))[0]?.name;
            const optionValueName = group_types.filter(t => t.id === group.type)[0]?.options.filter((o: any) => o.id === parseInt(optionType))[0]?.values.filter((v: any) => v.option === parseInt(optionType) && v.id === optionValue)[0]?.name;
            console.log("Option Type Name:", optionTypeName, "Option Value Name:", optionValueName);

            name = optionValueName + " " + name;

        })
    }

    return name;
}

export function evaluateGags(player: any) {
    const gagsLevels = {
        toonup: player.toonup,
        trap: player.trap,
        lure: player.lure,
        sound: player.sound,
        throw: player.throw,
        squirt: player.squirt,
        zap: player.zap, // TTCC only
        drop: player.drop,
    }

    let result = "";

    Object.keys(gagsLevels).forEach(gag => {
        result += gag.charAt(0).toUpperCase() + gag.charAt(1) + ": " + gagsLevels[gag] + " | ";
    })

    return result.trim();
}